const std = @import("std");
const enum_gen = @import("nri_enum_gen.zig");
const bitfield_gen = @import("nri_bitfield_gen.zig");
const container_gen = @import("nri_container_gen.zig");

const codegen_config = @embedFile("../codegen_config.zon");
pub const ConfigType = struct {
    enums: []const []const u8,
    bitfields: []const []const u8,
};
pub fn main(init: std.process.Init) !void {
    const alloc = init.arena.allocator();
    const cwd = std.Io.Dir.cwd();

    const output_dir = try cwd.createDirPathOpen(init.io, "zig_nri/codegen_out", .{});
    const config_file_path = "/home/danad/dev/zig/krajc_engine/NRI/zig_nri/codegen_out/codegen_config.zon";
    const config_file = try std.Io.Dir.openFileAbsolute(init.io, config_file_path, .{ .allow_directory = false, .mode = .read_only });
    defer config_file.close(init.io);
    const config_file_stat = try config_file.stat(init.io);
    const config_file_buff = try alloc.allocSentinel(u8, config_file_stat.size, 0);
    _ = try config_file.readStreaming(init.io, &[_][]u8{config_file_buff});

    var diagnostics: std.zon.parse.Diagnostics = .{};
    const config = std.zon.parse.fromSliceAlloc(ConfigType, alloc, config_file_buff, &diagnostics, .{}) catch |err| {
        const buffer = try alloc.alloc(u8, 1024 * 12);
        var writer = std.Io.File.stdout().writer(init.io, buffer);
        const writer_interface = &writer.interface;
        try diagnostics.format(writer_interface);
        try writer.flush();
        return err;
    };
    try std.Io.File.stdout().writeStreamingAll(init.io, "enums: \n");
    for (config.enums) |enum_name| {
        try std.Io.File.stdout().writeStreamingAll(init.io, try std.fmt.allocPrint(alloc, "\t{s}\n", .{enum_name}));
    }

    const input_file_path = "/home/danad/dev/zig/krajc_engine/NRI/zig_nri/nri.zig";
    const input_file = try std.Io.Dir.openFileAbsolute(init.io, input_file_path, .{ .allow_directory = false, .mode = .read_only });
    defer input_file.close(init.io);
    const input_file_stat = try input_file.stat(init.io);
    const input_file_buff = try alloc.allocSentinel(u8, input_file_stat.size, 0);
    _ = try input_file.readStreaming(init.io, &[_][]u8{input_file_buff});
    const output_file = try output_dir.createFile(init.io, "codegen.zig", .{ .truncate = true, .read = true });
    var output_file_stat = try output_file.stat(init.io);

    var input_tree = try std.zig.Ast.parse(alloc, input_file_buff, .zig);
    defer input_tree.deinit(alloc);
    const output_file_buffer = try alloc.alloc(u8, 1024 * 5);
    var output_writer_raw = output_file.writer(init.io, output_file_buffer);
    var output_writer = &output_writer_raw.interface;
    try output_writer.writeAll(
        \\// Generated by zig nri binding tools, modify the tools, not the generated code please
        \\pub const c = @import("../nri.zig");
        \\const std = @import("std");
    );

    try output_writer.writeAll("\n");

    var gen_alloc = std.heap.ArenaAllocator.init(alloc);
    defer gen_alloc.deinit();
    try enum_gen.enumGen(gen_alloc.allocator(), config.enums, &input_tree, output_writer);
    _ = gen_alloc.reset(.retain_capacity);
    try bitfield_gen.bitfieldGen(gen_alloc.allocator(), config.bitfields, &input_tree, output_writer);
    _ = gen_alloc.reset(.retain_capacity);
    try container_gen.containerGen(gen_alloc.allocator(), alloc, &config, &input_tree, output_writer);
    _ = gen_alloc.reset(.retain_capacity);

    const copy_file_path = "/home/danad/dev/zig/krajc_engine/NRI/zig_nri/codegen_out/unions.zig";
    const copy_file = try std.Io.Dir.openFileAbsolute(init.io, copy_file_path, .{ .allow_directory = false, .mode = .read_only });
    defer copy_file.close(init.io);
    const copy_stat = try copy_file.stat(init.io);
    const copy_buff = try alloc.alloc(u8, copy_stat.size);
    var copy_reader = copy_file.readerStreaming(init.io, copy_buff);
    try copy_reader.interface.readSliceAll(copy_buff);
    try output_writer.writeAll(copy_buff);

    try output_writer.flush();
    output_file_stat = try output_file.stat(init.io);
}

comptime {
    std.testing.refAllDecls(@This());
    std.testing.refAllDecls(container_gen);
}
